### ISSUE TITLE
Stereo Camera Setup

### ISSUE THREAD

**Issue by DrJohnDale** [uzh-rpg/rpg_esim#23]
Is there an example of how to setup a stereo simulation?

I am trying to create a stereo setup but both cameras give the same information and I cannot seem to offset one from the other.

I have made a .yaml file for two cameras (see below) and tried to separate them using the T_B_C matrices, but when the simulation has finished both sets of data in the ros bag look identical.

the .yaml file is
```
label: "simulated_camera"
id: 433585ebda8d1431223927a14788a127
cameras:
- camera:
    label: dvs0
    id: a0fba5412e961934d842d3a2a78e5cba
    line-delay-nanoseconds: 0
    image_height: 180
    image_width: 240
    type: pinhole
    intrinsics:
      cols: 1
      rows: 4
      data: [198.245521288, 198.277025706, 142.064861206, 100.903484508]
    distortion:
      type: equidistant
      parameters:
        cols: 1
        rows: 4
        data: [-0.0506755889541, 0.0456313630037, -0.0825742639337, 0.0557104403236]
  T_B_C:
    cols: 4
    rows: 4
    data: [1, 0, 0,  0,
           0, -1, 0, 0,
           0,  0, -1, 0,
           0, 0, 0, 1]
- camera:
    label: dvs1
    id: a0fba5412e961934d842d3a2a78e5cbb
    line-delay-nanoseconds: 0
    image_height: 180
    image_width: 240
    type: pinhole
    intrinsics:
      cols: 1
      rows: 4
      data: [198.245521288, 198.277025706, 142.064861206, 100.903484508]
    distortion:
      type: equidistant
      parameters:
        cols: 1
        rows: 4
        data: [-0.0506755889541, 0.0456313630037, -0.0825742639337, 0.0557104403236]
  T_B_C:
      cols: 4
      rows: 4
      data: [1, 0, 0,  100.0,
             0, -1, 0, 0.0,
             0,  0, -1, 0.0,
             0, 0, 0, 1]
```

I am using a modified version of the example.conf with this .yaml file. Do I need to add any other variables to get stereo to work?

Also in the T_B_C matrix what are the units for displacement?

In the simulation output it recognises that it is stereo
```
I0502 13:54:33.050158  8920 camera_rig.cpp:197] Camera 0 and 1: Overlap = 0.996667, Baseline = 100.0 -> Stereo Rig.
```
but the over lap is very high.

If i look at the camera info for the two cameras in the output ros bag they are the same when I would expect the projection matrix to have a shift.

```
cam 0

header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:   1000000
  frame_id: ''
height: 180
width: 240
distortion_model: "equidistant"
D: [-0.0506755889541, 0.0456313630037, -0.0825742639337, 0.0557104403236]
K: [198.245521288, 0.0, 142.064861206, 0.0, 198.277025706, 100.903484508, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [198.245521288, 0.0, 142.064861206, 0.0, 0.0, 198.277025706, 100.903484508, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

cam 1

header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:   1000000
  frame_id: ''
height: 180
width: 240
distortion_model: "equidistant"
D: [-0.0506755889541, 0.0456313630037, -0.0825742639337, 0.0557104403236]
K: [198.245521288, 0.0, 142.064861206, 0.0, 198.277025706, 100.903484508, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [198.245521288, 0.0, 142.064861206, 0.0, 0.0, 198.277025706, 100.903484508, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```

Thanks.
